#include "ResourcePacker.hpp"
#include "../../include/GravyEngine.hpp"

void CreateResourcePackFromFiles()
{
    ResourcePack pack;

    pack.AddFile("../res/Textures/Terrain/forrest_ground_01_diff_1k.jpg", "Textures/Terrain/forrest_ground_01_diff_1k.jpg");
    pack.AddFile("../res/Textures/Terrain/Mud.png", "Textures/Terrain/Mud.png");
    pack.AddFile("../res/Textures/Terrain/stuff/Grass (Lawn).jpg", "Textures/Terrain/stuff/Grass (Lawn).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Pebbles.jpg", "Textures/Terrain/stuff/Pebbles.jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Rock (Moss).jpg", "Textures/Terrain/stuff/Rock (Moss).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Forest Floor.jpg", "Textures/Terrain/stuff/Forest Floor.jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/DirtGrass.jpg", "Textures/Terrain/stuff/DirtGrass.jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Sand (with pebbles).jpg", "Textures/Terrain/stuff/Sand (with pebbles).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Rock (Basic).jpg", "Textures/Terrain/stuff/Rock (Basic).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Grass&Rock.jpg", "Textures/Terrain/stuff/Grass&Rock.jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Sand (Beach).jpg", "Textures/Terrain/stuff/Sand (Beach).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Sand (Beach Wet2).jpg", "Textures/Terrain/stuff/Sand (Beach Wet2).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Snow.jpg", "Textures/Terrain/stuff/Snow.jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Grass (Meadows2).jpg", "Textures/Terrain/stuff/Grass (Meadows2).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Rocky Dirt.jpg", "Textures/Terrain/stuff/Rocky Dirt.jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Grass (Muddy).jpg", "Textures/Terrain/stuff/Grass (Muddy).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Sand (Beach2).jpg", "Textures/Terrain/stuff/Sand (Beach2).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Grass (Meadows).jpg", "Textures/Terrain/stuff/Grass (Meadows).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Cliff (Sandstone).jpg", "Textures/Terrain/stuff/Cliff (Sandstone).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Cliff (Layered Rock).jpg", "Textures/Terrain/stuff/Cliff (Layered Rock).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Cliff (Grassy).jpg", "Textures/Terrain/stuff/Cliff (Grassy).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Path (Rocky).jpg", "Textures/Terrain/stuff/Path (Rocky).jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/GoodDirt.jpg", "Textures/Terrain/stuff/GoodDirt.jpg");
    pack.AddFile("../res/Textures/Terrain/stuff/Grass (Hill).jpg", "Textures/Terrain/stuff/Grass (Hill).jpg");
    pack.AddFile("../res/Textures/Terrain/coast_sand_rocks_02_diff_1k.jpg", "Textures/Terrain/coast_sand_rocks_02_diff_1k.jpg");
    pack.AddFile("../res/Textures/Terrain/GrassFlowers.png", "Textures/Terrain/GrassFlowers.png");
    pack.AddFile("../res/Textures/Splatmaps/Splatmap.jpg", "Textures/Splatmaps/Splatmap.jpg");
    pack.AddFile("../res/Textures/Particles/slash_02.png", "Textures/Particles/slash_02.png");
    pack.AddFile("../res/Textures/Particles/star_02.png", "Textures/Particles/star_02.png");
    pack.AddFile("../res/Textures/Particles/spark_07.png", "Textures/Particles/spark_07.png");
    pack.AddFile("../res/Textures/Particles/star_07.png", "Textures/Particles/star_07.png");
    pack.AddFile("../res/Textures/Particles/flame_06.png", "Textures/Particles/flame_06.png");
    pack.AddFile("../res/Textures/Particles/trace_02.png", "Textures/Particles/trace_02.png");
    pack.AddFile("../res/Textures/Particles/scorch_01.png", "Textures/Particles/scorch_01.png");
    pack.AddFile("../res/Textures/Particles/fire_01.png", "Textures/Particles/fire_01.png");
    pack.AddFile("../res/Textures/Particles/smoke_06.png", "Textures/Particles/smoke_06.png");
    pack.AddFile("../res/Textures/Particles/star_01.png", "Textures/Particles/star_01.png");
    pack.AddFile("../res/Textures/Particles/smoke_04.png", "Textures/Particles/smoke_04.png");
    pack.AddFile("../res/Textures/Particles/star_05.png", "Textures/Particles/star_05.png");
    pack.AddFile("../res/Textures/Particles/trace_06.png", "Textures/Particles/trace_06.png");
    pack.AddFile("../res/Textures/Particles/spark_05.png", "Textures/Particles/spark_05.png");
    pack.AddFile("../res/Textures/Particles/circle_05.png", "Textures/Particles/circle_05.png");
    pack.AddFile("../res/Textures/Particles/smoke_09.png", "Textures/Particles/smoke_09.png");
    pack.AddFile("../res/Textures/Particles/muzzle_04.png", "Textures/Particles/muzzle_04.png");
    pack.AddFile("../res/Textures/Particles/symbol_02.png", "Textures/Particles/symbol_02.png");
    pack.AddFile("../res/Textures/Particles/slash_04.png", "Textures/Particles/slash_04.png");
    pack.AddFile("../res/Textures/Particles/slash_03.png", "Textures/Particles/slash_03.png");
    pack.AddFile("../res/Textures/Particles/slash_01.png", "Textures/Particles/slash_01.png");
    pack.AddFile("../res/Textures/Particles/fire_02.png", "Textures/Particles/fire_02.png");
    pack.AddFile("../res/Textures/Particles/window_03.png", "Textures/Particles/window_03.png");
    pack.AddFile("../res/Textures/Particles/smoke_08.png", "Textures/Particles/smoke_08.png");
    pack.AddFile("../res/Textures/Particles/symbol_01.png", "Textures/Particles/symbol_01.png");
    pack.AddFile("../res/Textures/Particles/twirl_03.png", "Textures/Particles/twirl_03.png");
    pack.AddFile("../res/Textures/Particles/trace_04.png", "Textures/Particles/trace_04.png");
    pack.AddFile("../res/Textures/Particles/flame_04.png", "Textures/Particles/flame_04.png");
    pack.AddFile("../res/Textures/Particles/smoke_01.png", "Textures/Particles/smoke_01.png");
    pack.AddFile("../res/Textures/Particles/star_08.png", "Textures/Particles/star_08.png");
    pack.AddFile("../res/Textures/Particles/window_02.png", "Textures/Particles/window_02.png");
    pack.AddFile("../res/Textures/Particles/window_01.png", "Textures/Particles/window_01.png");
    pack.AddFile("../res/Textures/Particles/muzzle_01.png", "Textures/Particles/muzzle_01.png");
    pack.AddFile("../res/Textures/Particles/circle_01.png", "Textures/Particles/circle_01.png");
    pack.AddFile("../res/Textures/Particles/Rotated/trace_07_rotated.png", "Textures/Particles/Rotated/trace_07_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/spark_05_rotated.png", "Textures/Particles/Rotated/spark_05_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/flame_05_rotated.png", "Textures/Particles/Rotated/flame_05_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/trace_05_rotated.png", "Textures/Particles/Rotated/trace_05_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/muzzle_04_rotated.png", "Textures/Particles/Rotated/muzzle_04_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/trace_01_rotated.png", "Textures/Particles/Rotated/trace_01_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/spark_06_rotated.png", "Textures/Particles/Rotated/spark_06_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/muzzle_01_rotated.png", "Textures/Particles/Rotated/muzzle_01_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/trace_03_rotated.png", "Textures/Particles/Rotated/trace_03_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/trace_02_rotated.png", "Textures/Particles/Rotated/trace_02_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/trace_04_rotated.png", "Textures/Particles/Rotated/trace_04_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/muzzle_05_rotated.png", "Textures/Particles/Rotated/muzzle_05_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/trace_06_rotated.png", "Textures/Particles/Rotated/trace_06_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/flame_06_rotated.png", "Textures/Particles/Rotated/flame_06_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/muzzle_03_rotated.png", "Textures/Particles/Rotated/muzzle_03_rotated.png");
    pack.AddFile("../res/Textures/Particles/Rotated/muzzle_02_rotated.png", "Textures/Particles/Rotated/muzzle_02_rotated.png");
    pack.AddFile("../res/Textures/Particles/dirt_03.png", "Textures/Particles/dirt_03.png");
    pack.AddFile("../res/Textures/Particles/light_02.png", "Textures/Particles/light_02.png");
    pack.AddFile("../res/Textures/Particles/magic_03.png", "Textures/Particles/magic_03.png");
    pack.AddFile("../res/Textures/Particles/scratch_01.png", "Textures/Particles/scratch_01.png");
    pack.AddFile("../res/Textures/Particles/trace_07.png", "Textures/Particles/trace_07.png");
    pack.AddFile("../res/Textures/Particles/scorch_03.png", "Textures/Particles/scorch_03.png");
    pack.AddFile("../res/Textures/Particles/flame_01.png", "Textures/Particles/flame_01.png");
    pack.AddFile("../res/Textures/Particles/light_01.png", "Textures/Particles/light_01.png");
    pack.AddFile("../res/Textures/Particles/magic_05.png", "Textures/Particles/magic_05.png");
    pack.AddFile("../res/Textures/Particles/smoke_02.png", "Textures/Particles/smoke_02.png");
    pack.AddFile("../res/Textures/Particles/trace_03.png", "Textures/Particles/trace_03.png");
    pack.AddFile("../res/Textures/Particles/magic_04.png", "Textures/Particles/magic_04.png");
    pack.AddFile("../res/Textures/Particles/star_04.png", "Textures/Particles/star_04.png");
    pack.AddFile("../res/Textures/Particles/dirt_01.png", "Textures/Particles/dirt_01.png");
    pack.AddFile("../res/Textures/Particles/magic_01.png", "Textures/Particles/magic_01.png");
    pack.AddFile("../res/Textures/Particles/twirl_02.png", "Textures/Particles/twirl_02.png");
    pack.AddFile("../res/Textures/Particles/spark_03.png", "Textures/Particles/spark_03.png");
    pack.AddFile("../res/Textures/Particles/flare_01.png", "Textures/Particles/flare_01.png");
    pack.AddFile("../res/Textures/Particles/window_04.png", "Textures/Particles/window_04.png");
    pack.AddFile("../res/Textures/Particles/spark_04.png", "Textures/Particles/spark_04.png");
    pack.AddFile("../res/Textures/Particles/circle_04.png", "Textures/Particles/circle_04.png");
    pack.AddFile("../res/Textures/Particles/smoke_07.png", "Textures/Particles/smoke_07.png");
    pack.AddFile("../res/Textures/Particles/smoke_10.png", "Textures/Particles/smoke_10.png");
    pack.AddFile("../res/Textures/Particles/muzzle_05.png", "Textures/Particles/muzzle_05.png");
    pack.AddFile("../res/Textures/Particles/flame_05.png", "Textures/Particles/flame_05.png");
    pack.AddFile("../res/Textures/Particles/scorch_02.png", "Textures/Particles/scorch_02.png");
    pack.AddFile("../res/Textures/Particles/flame_02.png", "Textures/Particles/flame_02.png");
    pack.AddFile("../res/Textures/Particles/trace_01.png", "Textures/Particles/trace_01.png");
    pack.AddFile("../res/Textures/Particles/circle_03.png", "Textures/Particles/circle_03.png");
    pack.AddFile("../res/Textures/Particles/muzzle_02.png", "Textures/Particles/muzzle_02.png");
    pack.AddFile("../res/Textures/Particles/spark_02.png", "Textures/Particles/spark_02.png");
    pack.AddFile("../res/Textures/Particles/light_03.png", "Textures/Particles/light_03.png");
    pack.AddFile("../res/Textures/Particles/magic_02.png", "Textures/Particles/magic_02.png");
    pack.AddFile("../res/Textures/Particles/dirt_02.png", "Textures/Particles/dirt_02.png");
    pack.AddFile("../res/Textures/Particles/star_09.png", "Textures/Particles/star_09.png");
    pack.AddFile("../res/Textures/Particles/flame_03.png", "Textures/Particles/flame_03.png");
    pack.AddFile("../res/Textures/Particles/star_03.png", "Textures/Particles/star_03.png");
    pack.AddFile("../res/Textures/Particles/twirl_01.png", "Textures/Particles/twirl_01.png");
    pack.AddFile("../res/Textures/Particles/star_06.png", "Textures/Particles/star_06.png");
    pack.AddFile("../res/Textures/Particles/smoke_05.png", "Textures/Particles/smoke_05.png");
    pack.AddFile("../res/Textures/Particles/spark_06.png", "Textures/Particles/spark_06.png");
    pack.AddFile("../res/Textures/Particles/smoke_03.png", "Textures/Particles/smoke_03.png");
    pack.AddFile("../res/Textures/Particles/muzzle_03.png", "Textures/Particles/muzzle_03.png");
    pack.AddFile("../res/Textures/Particles/circle_02.png", "Textures/Particles/circle_02.png");
    pack.AddFile("../res/Textures/Particles/trace_05.png", "Textures/Particles/trace_05.png");
    pack.AddFile("../res/Textures/Particles/spark_01.png", "Textures/Particles/spark_01.png");
    pack.AddFile("../res/Textures/Misc/Road2.jpg", "Textures/Misc/Road2.jpg");
    pack.AddFile("../res/Textures/Misc/wallseamless.jpg", "Textures/Misc/wallseamless.jpg");
    pack.AddFile("../res/Textures/Misc/bubble.png", "Textures/Misc/bubble.png");
    pack.AddFile("../res/Textures/Misc/Box.jpg", "Textures/Misc/Box.jpg");
    pack.AddFile("../res/Textures/Misc/GravyLogoTransparent.png", "Textures/Misc/GravyLogoTransparent.png");
    pack.AddFile("../res/Textures/Misc/TextExample.png", "Textures/Misc/TextExample.png");
    pack.AddFile("../res/Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_AO.png", "Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_AO.png");
    pack.AddFile("../res/Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_Roughness.png", "Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_Roughness.png");
    pack.AddFile("../res/Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_Height.png", "Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_Height.png");
    pack.AddFile("../res/Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_Normal.png", "Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_Normal.png");
    pack.AddFile("../res/Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_Metallic.png", "Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_Metallic.png");
    pack.AddFile("../res/Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_BaseColor.png", "Textures/Misc/Metal/Rusty/RustyCorrugatedMetalPanel02_1K_BaseColor.png");
    pack.AddFile("../res/Textures/Misc/Knob70_89.png", "Textures/Misc/Knob70_89.png");
    pack.AddFile("../res/Textures/Misc/Knob71_101.png", "Textures/Misc/Knob71_101.png");
    pack.AddFile("../res/Textures/Misc/Road.jpg", "Textures/Misc/Road.jpg");
    pack.AddFile("../res/Textures/Water/Water.jpg", "Textures/Water/Water.jpg");
    pack.AddFile("../res/Textures/Heightmaps/Heightmap2.png", "Textures/Heightmaps/Heightmap2.png");
    pack.AddFile("../res/Textures/Heightmaps/bushroadheightmap.jpg", "Textures/Heightmaps/bushroadheightmap.jpg");
    pack.AddFile("../res/Textures/Heightmaps/Heightmap4.png", "Textures/Heightmaps/Heightmap4.png");
    pack.AddFile("../res/Textures/Heightmaps/Heightmap3.png", "Textures/Heightmaps/Heightmap3.png");
    pack.AddFile("../res/Textures/Heightmaps/Heightmap1.png", "Textures/Heightmaps/Heightmap1.png");
    pack.AddFile("../res/Audio/law_-_240201-01_130_Ebm.mp3", "Audio/law_-_240201-01_130_Ebm.mp3");
    pack.AddFile("../res/Audio/drumpoekel.mp3", "Audio/drumpoekel.mp3");
    pack.AddFile("../res/Audio/WB24082019.mp3", "Audio/WB24082019.mp3");
    pack.AddFile("../res/Audio/WB25122020.mp3", "Audio/WB25122020.mp3");
    pack.AddFile("../res/Audio/WB07042020.mp3", "Audio/WB07042020.mp3");
    pack.AddFile("../res/Audio/WB21022020.mp3", "Audio/WB21022020.mp3");
    pack.AddFile("../res/Audio/WB21042021.mp3", "Audio/WB21042021.mp3");
    pack.AddFile("../res/Audio/WB17042021.mp3", "Audio/WB17042021.mp3");
    pack.AddFile("../res/Audio/WB12092019.mp3", "Audio/WB12092019.mp3");
    pack.AddFile("../res/Audio/WB03072020.mp3", "Audio/WB03072020.mp3");
    pack.AddFile("../res/Audio/law_-_220806-01_120_Gm_Master_240209.mp3", "Audio/law_-_220806-01_120_Gm_Master_240209.mp3");
    pack.AddFile("../res/Audio/WB07102019.mp3", "Audio/WB07102019.mp3");
    pack.AddFile("../res/Audio/WB16042021_vocals.mp3", "Audio/WB16042021_vocals.mp3");
    pack.AddFile("../res/Audio/WB16042021.mp3", "Audio/WB16042021.mp3");
    pack.AddFile("../res/Audio/law_-_230422-02_v1.01.mp3", "Audio/law_-_230422-02_v1.01.mp3");
    pack.AddFile("../res/Audio/PropellerEngine.wav", "Audio/PropellerEngine.wav");
    pack.AddFile("../res/Audio/Beats_by_Law_-_240217-01_96_Gm_Tangeray.mp3", "Audio/Beats_by_Law_-_240217-01_96_Gm_Tangeray.mp3");
    pack.AddFile("../res/Audio/Beats_by_Law_-_230422-02_160_Fm_Automatic.mp3", "Audio/Beats_by_Law_-_230422-02_160_Fm_Automatic.mp3");
    pack.AddFile("../res/Audio/WB30082017.mp3", "Audio/WB30082017.mp3");
    pack.AddFile("../res/Audio/law_-_240131-01_124_Dm.mp3", "Audio/law_-_240131-01_124_Dm.mp3");
    pack.AddFile("../res/Audio/WB19042021.mp3", "Audio/WB19042021.mp3");
    pack.AddFile("../res/Audio/law_-_230422-02_-_v1.01_-_Drake_-_Jimmy_Cooks.mp3", "Audio/law_-_230422-02_-_v1.01_-_Drake_-_Jimmy_Cooks.mp3");
    pack.AddFile("../res/Audio/WB23042020.mp3", "Audio/WB23042020.mp3");
    pack.AddFile("../res/Audio/Kick.mp3", "Audio/Kick.mp3");
    pack.AddFile("../res/Audio/law_-_230808-02_-_Bandmanrill_-_Copy_and_Paste.mp3", "Audio/law_-_230808-02_-_Bandmanrill_-_Copy_and_Paste.mp3");
    pack.AddFile("../res/Audio/WB30082019.mp3", "Audio/WB30082019.mp3");
    pack.AddFile("../res/Audio/law_-_220207-01.mp3", "Audio/law_-_220207-01.mp3");

    pack.SavePack("assets.dat", "assets.dat");
}