#ifndef GRAVYENGINE_GRAVYENGINE_HPP
#define GRAVYENGINE_GRAVYENGINE_HPP

#include "System/Environment.hpp"
#include "System/Numerics/Vector4.hpp"
#include "System/Numerics/Matrix4.hpp"
#include "System/Numerics/LatLongPoint.hpp"
#include "System/Numerics/Matrix3.hpp"
#include "System/Numerics/Vector2.hpp"
#include "System/Numerics/Quaternion.hpp"
#include "System/Numerics/Vector3.hpp"
#include "System/Mathf.hpp"
#include "System/DateTime.hpp"
#include "System/EventHandler.hpp"
#include "System/ConcurrentList.hpp"
#include "System/Drawing/Color.hpp"
#include "System/Drawing/Image.hpp"
#include "System/Random.hpp"
#include "Rendering/Shader.hpp"
#include "Rendering/Mesh.hpp"
#include "Rendering/Materials/DiffuseMaterial.hpp"
#include "Rendering/Material.hpp"
#include "Rendering/Graphics.hpp"
#include "Rendering/Vertex.hpp"
#include "Rendering/MeshRenderer.hpp"
#include "Rendering/Shaders/DiffuseShader.hpp"
#include "Rendering/Texture2D.hpp"
#include "Rendering/Texture.hpp"
#include "Rendering/Renderer.hpp"
#include "Rendering/Buffers/VertexBufferObject.hpp"
#include "Rendering/Buffers/ElementBufferObject.hpp"
#include "Rendering/Buffers/VertexArrayObject.hpp"
#include "Audio/AudioBuffer.hpp"
#include "Audio/AudioContext.hpp"
#include "Audio/DSP/Oscillator.hpp"
#include "Audio/DSP/FilterEffect.hpp"
#include "Audio/DSP/NoiseCalculator.hpp"
#include "Audio/DSP/NoiseGenerator.hpp"
#include "Audio/DSP/WaveCalculator.hpp"
#include "Audio/DSP/Wavetable.hpp"
#include "Audio/DSP/AudioEffect.hpp"
#include "Audio/DSP/FMGenerator.hpp"
#include "Audio/DSP/Filter.hpp"
#include "Audio/DSP/AudioGenerator.hpp"
#include "Audio/AudioSource.hpp"
#include "Audio/AudioClip.hpp"
#include "Audio/AudioListener.hpp"
#include "Core/GameBehaviourManager.hpp"
#include "Core/Screen.hpp"
#include "Core/GameObject.hpp"
#include "Core/Debug.hpp"
#include "Core/Object.hpp"
#include "Core/GameBehaviour.hpp"
#include "Core/Camera.hpp"
#include "Core/Component.hpp"
#include "Core/Time.hpp"
#include "Core/Application.hpp"
#include "Core/Transform.hpp"
#include "Core/Input.hpp"
#include "Core/FirstPersonCamera.hpp"

#include "External/imgui/imgui.h"

using namespace GravyEngine;

#endif